### ISSUE TITLE
extract-user-settings migration never recovers

### ISSUE THREAD

**Issue by mandric** [medic/medic-api#57]
In `extract-user-settings` migration, if it fails part way through it can never recover because it will continue trying to insert docs without a _rev field for docs that already exist resulting in 409s.  We might fix by using bulk_docs api with all-or-nothing flag so all docs get inserted or nothing happens.  Or check if the doc exists first and ignore it if it does.  Related: https://github.com/medic/medic-api/issues/52

**Comment by garethbowen** [comment]
I think the check and ignore approach is better because on a large database it'd be good to make gradual progress and at least get _some_ users working.

**Comment by estellecomment** [comment]
Fixed by https://github.com/medic/medic-api/commit/d824446cb7ca9f281d549db21af6b4146a71b621
Third solution : check if the doc exists already and ignore it if it does.

Assigning @mandric for code review.

**Comment by mandric** [comment]
Looks good, just some cosmetic things I noticed.

**Comment by mandric** [comment]
Also fwiw, I think using _bulk_docs would probably get us what we want too.  Without the `all-or-nothing` flag a bulk docs request could fail with 409 on some docs and succeed on others, we could check the response data to know what happened and whether we want to ignore it.  In general I think the more we use bulk docs (and experience we gain) the better but that can wait until the next issue.

**Comment by estellecomment** [comment]
Done! Thanks for the review.

Hmm, the all-migration-or-no-migration effect would be nice indeed. The bulk queries could get too big on large databases though, we'd have to run them in several batches, so that would be less nice.

Though for this migration, the number of users on .4 instances is never more than a dozen, from what I've seen, so it would work fine. We could still implement batching in case a system like LG's runs it (by mistake I guess, since it doesn't need it), cos it has 800+ users (!!!).

Should I close this issue then @mandric ?
