### ISSUE TITLE
runs out of memory and crashed during bulk updates

### ISSUE THREAD

**Issue by mandric** [medic/medic-api#96]
When sending large body of data through like during a bulk update, medic-api crashes with something that couchdb can handle without much trouble.  The bulk docs body I sent through was about 15M or 3000 docs.

```
2016-08-18T00:41:43.191Z - info: 127.0.0.1 - admin [18/Aug/2016:00:41:43 +0000] "POST /medic/_bulk_docs HTTP/1.0" - - "-" "curl/7.43.0"

2016-08-18T00:47:25.183Z - error: FATAL ERROR: CALL_AND_RETRY_LAST Allocation failed - process out of memory

2016-08-18T00:47:28.370Z - info: Medic API listening on port 5988
```

**Comment by alxndrsn** [comment]
If `_bulk_update` calls are passed straight through from `medic-api` to couch, could nginx just proxy directly to couch, missing out api altogether?

**Comment by SCdF** [comment]
So on the one hand this would mean that nginx would become a development dependency (ie you'd need it installed, running and configured correctly).

_However_, if we're happy with development being slightly different (and since we don't have compression or https locally there is a good argument to say we are) then we could keep the support for medic-api proxying everything it doesn't understand, but then in production configurations have nginx get to it first.

**Comment by alxndrsn** [comment]
> if we're happy with development being slightly different

Sounds convenient to me.  If we did this I think it would be important to have nginx running in Travis for e2e & integration tests.

**Comment by garethbowen** [comment]
The real problem with bypassing api is you're also bypassing our permissions layer.

**Comment by mandric** [comment]
We also need it for auditing.

**Comment by mandric** [comment]
Just ran a few 30M bulk updates (`_bulk_docs` request) with 5000 docs without a problem on 2.8.2.  Anyone know offhand if [changes between 2.7.2 and 2.8.2](https://github.com/medic/medic-api/compare/2.7.3...2.8.2) affected this issue?

**Comment by garethbowen** [comment]
Closing this as it hasn't happened in a while. Reopen in medic-webapp if it happens again.
